name: Build Brave Android ARM64

on:
  push:
    branches: [master]

env:
  NODE_VERSION: 20
  ANDROID_NDK_VERSION: 25.2.9519653

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install core dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          git \
          python3 \
          python3-venv \
          python3-pip \
          lsb-release \
          curl \
          unzip
        
        # Set up Python tools
        python3 -m ensurepip --upgrade
        python3 -m pip install --upgrade pip setuptools wheel

    - name: Install Chromium build dependencies
      run: |
        yes | sudo ./src/build/install-build-deps.sh --android --arm --unsupported
      env:
        CHROME_DEVEL_SANDBOX: /usr/local/sbin/chrome-devel-sandbox
        
    - name: Install Chromium build dependencies
      run: |
        yes | sudo ./src/build/install-build-deps.sh --android --arm

    - name: Set up Android SDK/NDK
      uses: android-actions/setup-android@v3
      with:
        ndk-version: ${{ env.ANDROID_NDK_VERSION }}
        sdk-platform: android-34

    - name: npm install
      run: npm install
      working-directory: ./src/brave

    - name: Configure build
      run: |
        npm config set target_os android
        npm config set target_arch arm64
      working-directory: ./src/brave

    - name: Initialize build
      run: npm run init -- --target_os=android --target_arch=arm64
      working-directory: ./src/brave

    - name: Build Release
      run: npm run build Release
      working-directory: ./src/brave

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: brave-arm64-release
        path: |
          src/brave/out/android_arm64/Release/apks/*.apk
