name: Build Brave Browser APK

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip git wget unzip build-essential python3-distutils
          sudo pip3 install --upgrade pip
          sudo pip3 install depot_tools

      - name: Initialize Brave Environment
        run: |
          npm install
          npm run init

      - name: Build APK
        run: |
          npm run build -- Debug --target_os=android --target_arch=arm64 --target_android_output_format=apk --target_android_base=mono

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: BraveBrowser-arm64.apk
          path: src/out/android/arm64/apks/BraveBrowser.apk
          
